# Generated by Django 3.2.2 on 2021-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Titulo')),
                ('dia', models.IntegerField(max_length=100, null=True, verbose_name='Plazo de Pago')),
                ('tiemp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo Diferido')),
                ('desc', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, max_length=True, verbose_name='Descuento %')),
                ('tipo', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], max_length=100, verbose_name='Tipo de Pago')),
            ],
            options={
                'verbose_name': 'Pricelist',
                'verbose_name_plural': 'PriceList',
                'ordering': ['-id'],
            },
        ),
    ]
