# Generated by Django 3.2.2 on 2021-11-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='dia',
            field=models.IntegerField(null=True, verbose_name='Plazo de Pago'),
        ),
    ]
