# Generated by Django 3.2.2 on 2021-11-23 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20211123_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='state',
            field=models.CharField(choices=[('Realizada', 'Realizada'), ('Rechazada', 'Rechazada'), ('Recibida', 'Recibida')], default='Realizada', max_length=100),
        ),
        migrations.CreateModel(
            name='StockMovementOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(default=0.0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.provider')),
            ],
        ),
    ]
