# Generated by Django 3.2.2 on 2021-11-23 20:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0005_auto_20211123_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(default=0.0)),
                ('concepto', models.CharField(max_length=100, verbose_name='Concepto')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('state', models.CharField(choices=[('Realizada', 'Realizada'), ('Rechazada', 'Rechazada'), ('Recibida', 'Recibida')], default='Realizada', max_length=50)),
                ('bdestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bdestino_fixturetables', to='pos.sucursal', verbose_name='Destino')),
                ('brigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brigen_fixturetables', to='pos.sucursal', verbose_name='Origen')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementOperationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
                ('stockmovementoperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.stockmovementoperation')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalle de Transferencias',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='StockMovementOrder',
        ),
    ]
