# Generated by Django 3.2.2 on 2021-11-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20211123_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovementoperationdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovementoperationdetail',
            name='stockmovementoperation',
        ),
        migrations.DeleteModel(
            name='StockMovementOperation',
        ),
        migrations.DeleteModel(
            name='StockMovementOperationDetail',
        ),
    ]
