# Generated by Django 3.2.2 on 2021-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_productbysucursal_productbysucursaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='state',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Aprobar', 'Aprobar'), ('Recibir', 'Recibido')], default='Enviado', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='state',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Aprobar', 'Aprobar'), ('Recibir', 'Recibido')], default='Enviado', max_length=50),
        ),
    ]
