# Generated by Django 3.2.2 on 2021-12-09 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0009_auto_20211209_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionMercaderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numfact', models.CharField(max_length=150, verbose_name='NumeroFactura')),
                ('state', models.CharField(choices=[('Enviado', 'Enviado'), ('Aprobar', 'Aprobar'), ('Recibir', 'Recibido')], default='Recibido', max_length=150)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('demanda', models.IntegerField(default=0)),
                ('cantrecibida', models.IntegerField(default=0)),
                ('concepto', models.CharField(max_length=100, verbose_name='Concepto')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.provider')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sucursal')),
            ],
            options={
                'verbose_name': 'Recepcion Mercaderia',
                'verbose_name_plural': 'Recepcion Mercaderia',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionMercaderiaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
                ('recepcionmercaderia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.recepcionmercaderia')),
            ],
            options={
                'verbose_name': 'Detalle de Recepcion',
                'verbose_name_plural': 'Detalle de Recepcion',
                'ordering': ['-id'],
            },
        ),
    ]
