# Generated by Django 3.2.2 on 2021-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_recepcionmercaderia_recepcionmercaderiadetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionmercaderia',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='recepcionmercaderiadetail',
            name='cant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recepcionmercaderiadetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
